services:
  postgres-ecommerce:
    image: postgres
    container_name: postgres-ecommerce
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - postgres-ecommerce:/var/lib/postgresql
      - ./sql-init:/docker-entrypoint-initdb.d
    ports:
      - 8023:5432
    networks:
      - db_network_ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 3s

  pgadmin-ecommerce:
    image: dpage/pgadmin4
    container_name: pgadmin-ecommerce
    depends_on:
      - postgres-ecommerce
    environment:
      PMA_HOST: postgres-ecommerce
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8024:80
    volumes:
      - pgadmin-data-ecommerce:/var/lib/pgadmin
    networks:
      - db_network_ecommerce

  python-ecommerce:
    build: .
    container_name: python-ecommerce
    ports:
      - 8825:5000
    networks:
      - db_network_ecommerce
    volumes:
      - ./rapport:/home/thierry/rapport

volumes:
  postgres-ecommerce:
  pgadmin-data-ecommerce:

networks:
  db_network_ecommerce: