services:
  postgres-ecommerce:
    image: postgres
    container_name: postgres-ecommerce
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 8023:5432
    networks:
      - db_network_ecommerce

  pgadmin-ecommerce:
    image: dpage/pgadmin4
    container_name: pgadmin-ecommerce
    depends_on:
      - postgres-ecommerce
    environment:
      PMA_HOST: postgres-ecommerce
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8024:80
    volumes:
      - pgadmin-data-ecommerce:/var/lib/pgadmin
    networks:
      - db_network_ecommerce

  python-ecommerce:
    build: .
    container_name: python-ecommerce
    ports:
      - 8825:5000
    networks:
      - db_network_ecommerce

volumes:
  pgadmin-data-ecommerce:

networks:
  db_network_ecommerce: